Todo.create!(title: 'Buy bread', priority: 1)
Todo.create!(title: 'Buy butter', priority: 2)
Todo.create!(title: 'Buy tomatos', priority: 3)
Todo.create!(title: 'Pick up laundry', priority: 4)
Todo.create!(title: 'Pay the bills', priority: 5)
